services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
